swagger: '2.0'
info:
  version: 1.0.0
  title: CinemApp
  description: CinemApp API Docs
  contact:
    email: nicolasbertillod@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
schemes: [http, https]
host: localhost:3000
basePath: /api
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml