{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "CinemApp",
    "description": "CinemApp API Docs",
    "contact": {
      "email": "nicolasbertillod@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "schemes": [
    "http",
    "https"
  ],
  "host": "localhost:3000",
  "basePath": "/api",
  "paths": {
    "/user": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get all the Users",
        "description": "Get all the Users",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Users fetched successfully",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          },
          "400": {
            "description": "Error in fetching Users",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          }
        }
      },
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Save a new User",
        "description": "Save a new User",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "User object",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User saved successfully",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          },
          "400": {
            "description": "Error in saving User",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          }
        }
      }
    },
    "/user/{id}": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get a User",
        "description": "Get a User with the id specified in parameter",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "User id that needs to be fetched",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "User fetched successfully",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Error in fetching User",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          }
        }
      },
      "put": {
        "tags": [
          "User"
        ],
        "summary": "Update a User",
        "description": "Update a User",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "User id that needs to be updated",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "description": "User object",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User updated successfully",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          },
          "400": {
            "description": "Error in updating User",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "User"
        ],
        "summary": "Delete a User",
        "description": "Delete a User with the id specified in parameter",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "User id that needs to be deleted",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "User deleted successfully",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          },
          "400": {
            "description": "Error in deleting User",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          }
        }
      }
    },
    "/cinema": {
      "get": {
        "tags": [
          "Cinema"
        ],
        "summary": "Get all the Cinemas",
        "description": "Get all the Cinemas",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Cinemas fetched successfully",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Cinema"
              }
            }
          },
          "400": {
            "description": "Error in fetching Cinemas",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          }
        }
      },
      "post": {
        "tags": [
          "Cinema"
        ],
        "summary": "Save a new Cinema",
        "description": "Save a new Cinema",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Cinema object",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cinema"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Cinema saved successfully",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          },
          "400": {
            "description": "Error in saving Cinema",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          }
        }
      }
    },
    "/cinema/{id}": {
      "get": {
        "tags": [
          "Cinema"
        ],
        "summary": "Get a Cinema",
        "description": "Get a Cinema with the id specified in parameter",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "Cinema id that needs to be fetched",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Cinema fetched successfully",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cinema"
            }
          },
          "400": {
            "description": "Error in fetching Cinema",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          }
        }
      },
      "put": {
        "tags": [
          "Cinema"
        ],
        "summary": "Update a Cinema",
        "description": "Update a Cinema",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "Cinema id that needs to be updated",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "description": "Cinema object",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Cinema"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Cinema updated successfully",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          },
          "400": {
            "description": "Error in updating Cinema",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Cinema"
        ],
        "summary": "Delete a Cinema",
        "description": "Delete a Cinema with the id specified in parameter",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "Cinema id that needs to be deleted",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Cinema deleted successfully",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          },
          "400": {
            "description": "Error in deleting Cinema",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/CommonResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CommonResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "username": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "password": {
          "type": "string"
        },
        "company": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "email",
        "password"
      ]
    },
    "Cinema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "street": {
          "type": "string"
        },
        "street_num": {
          "type": "integer"
        },
        "state": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "latitude": {
          "type": "number"
        },
        "longitude": {
          "type": "number"
        },
        "price": {
          "type": "number"
        },
        "enabled": {
          "type": "boolean"
        }
      }
    }
  }
}
