---
openapi: "3.0.3"
info:
  description: "This is the API Documentation for UADEDAI CinemApp"
  version: "0.0.1"
  title: "CinemApp"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "nicolasbertillod@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: https://api.example.com/v1
    description: Production server (uses live data)
  - url: https://sandbox-api.example.com:8443/v1
    description: Sandbox server (uses test data)
host: ""
basePath: "/v1"
tags:
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about this project"
    url: "https://github.com/UADEDAI/Backend"
schemes:
- "https"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
paths:
  $ref: ./paths/User.yaml
definitions:
  $ref: ./paths/ApiResponse.yaml
  $ref: ./paths/User.yaml